### ISSUE TITLE
Epic: Settings page

### ISSUE THREAD

**Issue by mishildesai** [mishildesai/Journal-App#5]
This is the epic for the Settings page.

**Stories**
- [x] As a user, I'd like open the settings page from the app bar #4 
- [x] As a user, I'd like to see a settings page when I open it from the app bar #4
- [ ] As a user, I'd like to change the theme of the app globally in the settings page
- [ ] As a user, I'd like to see information about the app in the settings page
